INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Florian', 'Klausner');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Simon', 'Knogler');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Sebastian', 'Scholl');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Jonas', 'Wiesinger');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Silvio', 'Kalinke');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Jakob', 'Ratzenböck');
INSERT INTO PERSON (FIRST_NAME, LAST_NAME) VALUES ('Meris', 'Besic');

INSERT INTO VEHICLE (BRAND, MODEL, LASTNAME) VALUES ('Renault', 'CLIO', 'Klausner');
INSERT INTO VEHICLE (BRAND, MODEL, LASTNAME) VALUES ('Ford', 'Focus', 'Knogler');
INSERT INTO VEHICLE (BRAND, MODEL, LASTNAME) VALUES ('Citroen', 'C1', 'Scholl');
INSERT INTO VEHICLE (BRAND, MODEL, LASTNAME) VALUES ('Opel', 'Astra', 'Wiesinger');
INSERT INTO VEHICLE (BRAND, MODEL, LASTNAME) VALUES ('Volkswagen', 'Polo', 'Kalinke');
INSERT INTO VEHICLE (BRAND, MODEL, LASTNAME) VALUES ('Citroen', 'C4 Picasso', 'Ratzenböck');
INSERT INTO VEHICLE (BRAND, MODEL, LASTNAME) VALUES ('Fiat', 'Tipo', 'Besic');

INSERT INTO REGISTRATION (ENDDATE, REGISTRATIONPLATE, STARTDATE, VEHICLE_ID, PERSON_ID)
VALUES ('2026-05-01', 'LL-932-PN', '2019-08-14', 1, 1);
INSERT INTO REGISTRATION (ENDDATE, REGISTRATIONPLATE, STARTDATE, VEHICLE_ID, PERSON_ID)
VALUES ('2028-04-11', 'EF-427-CF', '2017-07-20', 2, 2);
INSERT INTO REGISTRATION (ENDDATE, REGISTRATIONPLATE, STARTDATE, VEHICLE_ID, PERSON_ID)
VALUES ('2025-10-16', 'GR-420-PP', '2019-02-13', 3, 3);
INSERT INTO REGISTRATION (ENDDATE, REGISTRATIONPLATE, STARTDATE, VEHICLE_ID, PERSON_ID)
VALUES ('2023-11-02', 'WE-691-QR', '2020-10-19', 4, 4);
INSERT INTO REGISTRATION (ENDDATE, REGISTRATIONPLATE, STARTDATE, VEHICLE_ID, PERSON_ID)
VALUES ('2027-07-21', 'SD-123-MR', '2016-09-21', 5, 5);
INSERT INTO REGISTRATION (ENDDATE, REGISTRATIONPLATE, STARTDATE, VEHICLE_ID, PERSON_ID)
VALUES ('2022-11-17', 'UU-893-NG', '2018-12-11', 6, 6);
INSERT INTO REGISTRATION (ENDDATE, REGISTRATIONPLATE, STARTDATE, VEHICLE_ID, PERSON_ID)
VALUES ('2030-08-12', 'AM-654-ML', '2014-09-03', 7, 7);



